"""Video generation domain contracts."""

from proovy_agent.features.video.exceptions import (
    InvalidSolutionPlanError,
    PermanentFailure,
    PipelineError,
    TransientFailure,
    classify_failure,
)
from proovy_agent.features.video.models import (
    DirectorBriefPolicy,
    FailureKind,
    FinalVideoArtifact,
    RenderedSegment,
    ScriptSegment,
    SegmentTTSResult,
    SolutionPlan,
    SolutionStep,
    StageName,
    TargetSelection,
    UserDiagnostic,
    UserErrorCode,
    VideoHints,
    VideoJobInput,
    VideoOptions,
    VideoPipelineJob,
    VideoPipelineResult,
    VideoScript,
    user_error_message,
)

__all__ = [
    "DirectorBriefPolicy",
    "FailureKind",
    "FinalVideoArtifact",
    "InvalidSolutionPlanError",
    "PermanentFailure",
    "PipelineError",
    "RenderedSegment",
    "ScriptSegment",
    "SegmentTTSResult",
    "SolutionPlan",
    "SolutionStep",
    "StageName",
    "TargetSelection",
    "TransientFailure",
    "UserDiagnostic",
    "UserErrorCode",
    "VideoHints",
    "VideoJobInput",
    "VideoOptions",
    "VideoPipelineJob",
    "VideoPipelineResult",
    "VideoScript",
    "classify_failure",
    "user_error_message",
]
