"""Deterministic Manim source builders for Phase A visual types."""

from __future__ import annotations

from dataclasses import dataclass
import re
import textwrap

_CJK_FONT = "Noto Sans CJK KR"
_CJK_PATTERN = re.compile(r"[\u1100-\u11ff\u3130-\u318f\uac00-\ud7a3\u4e00-\u9fff]")


@dataclass(frozen=True, slots=True)
class DeterministicTemplateRender:
    """Render-ready output generated by a deterministic visual template."""

    visual_type: str
    scene_class_name: str
    manim_source: str
    diagnostics: dict[str, object]

    def as_diagnostics(self) -> dict[str, object]:
        """Return a JSON-serializable diagnostics payload for render stage output."""
        return {
            "kind": "manim_source",
            "visual_type": self.visual_type,
            "scene_class_name": self.scene_class_name,
            "manim_source": self.manim_source,
            **self.diagnostics,
        }


_COMMON_MANIM_SOURCE = f"""
from manim import *

CJK_FONT = {_CJK_FONT!r}
CJK_TEX_TEMPLATE = TexTemplate(tex_compiler="xelatex", output_format=".xdv")
CJK_TEX_TEMPLATE.add_to_preamble(r\"\"\"
\\usepackage{{amsmath}}
\\usepackage{{amssymb}}
\\usepackage{{xeCJK}}
\\setCJKmainfont{{{_CJK_FONT}}}
\\setmainfont{{{_CJK_FONT}}}
\"\"\")


def _fit(mobject, max_width=12.0, max_height=6.4):
    if mobject.width > max_width:
        mobject.scale_to_fit_width(max_width)
    if mobject.height > max_height:
        mobject.scale_to_fit_height(max_height)
    return mobject


def _safe_text(value, font_size=32, color=WHITE, weight="NORMAL"):
    return Text(
        value,
        font=CJK_FONT,
        font_size=font_size,
        color=color,
        weight=weight,
        should_center=True,
    )


def _safe_math(value, font_size=52, color=WHITE):
    return MathTex(
        value,
        tex_template=CJK_TEX_TEMPLATE,
        font_size=font_size,
        color=color,
    )


def _text_block(lines, font_size=30, color=WHITE, bullet=False):
    safe_lines = lines or [""]
    objects = []
    for line in safe_lines:
        prefix = "\\u2022 " if bullet else ""
        objects.append(_safe_text(prefix + line, font_size=font_size, color=color))
    group = VGroup(*objects)
    group.arrange(DOWN, aligned_edge=LEFT, buff=0.16)
    return _fit(group)
"""


def _strip_required(value: str, field_name: str) -> str:
    stripped = value.strip()
    if not stripped:
        raise ValueError(f"{field_name} must not be empty")
    return stripped


def _normalize_optional_lines(values: list[str] | tuple[str, ...] | None) -> list[str]:
    if values is None:
        return []
    return [str(value).strip() for value in values if str(value).strip()]


def _wrap_text(value: str, *, width: int, max_lines: int) -> list[str]:
    stripped = _strip_required(value, "text")
    wrapped = textwrap.wrap(stripped, width=width, break_long_words=False)
    lines = wrapped or [stripped]
    if len(lines) <= max_lines:
        return lines
    return [*lines[: max_lines - 1], f"{lines[max_lines - 1]}..."]


def _contains_cjk(*values: object) -> bool:
    return any(_CJK_PATTERN.search(str(value)) is not None for value in values)


def _scene_source(scene_source: str) -> str:
    return f"{_COMMON_MANIM_SOURCE}\n\n{textwrap.dedent(scene_source).strip()}\n"


def _build_render(
    *,
    visual_type: str,
    scene_class_name: str,
    scene_source: str,
    text_line_count: int,
    math_expression_count: int,
    visual_description: str,
    emphasis_targets: list[str],
    contains_cjk: bool,
) -> DeterministicTemplateRender:
    return DeterministicTemplateRender(
        visual_type=visual_type,
        scene_class_name=scene_class_name,
        manim_source=_scene_source(scene_source),
        diagnostics={
            "cjk_font": _CJK_FONT,
            "uses_cjk_tex_template": True,
            "contains_cjk_text": contains_cjk,
            "text_line_count": text_line_count,
            "math_expression_count": math_expression_count,
            "visual_description": visual_description,
            "emphasis_targets": emphasis_targets,
        },
    )


def render_intro_problem(
    *,
    title: str,
    problem_text: str,
    visual_description: str,
    hints: list[str] | None = None,
    emphasis_targets: list[str] | None = None,
) -> DeterministicTemplateRender:
    """Build a deterministic problem-introduction Manim scene."""
    title_text = _strip_required(title, "title")
    description = _strip_required(visual_description, "visual_description")
    problem_lines = _wrap_text(problem_text, width=34, max_lines=5)
    hint_lines = _normalize_optional_lines(hints)[:3]
    targets = _normalize_optional_lines(emphasis_targets)
    scene_class_name = "IntroProblemScene"
    return _build_render(
        visual_type="intro_problem",
        scene_class_name=scene_class_name,
        scene_source=f"""
        class {scene_class_name}(Scene):
            def construct(self):
                title = _safe_text({title_text!r}, font_size=42, color=BLUE_E, weight="BOLD")
                title.to_edge(UP, buff=0.5)
                problem = _text_block({problem_lines!r}, font_size=30, color=WHITE)
                problem.next_to(title, DOWN, buff=0.55)
                pieces = [title, problem]
                if {hint_lines!r}:
                    hints = _text_block({hint_lines!r}, font_size=24, color=GREY_B, bullet=True)
                    hints.next_to(problem, DOWN, buff=0.42)
                    pieces.append(hints)
                layout = VGroup(*pieces)
                _fit(layout, max_width=12.0, max_height=6.4)
                layout.move_to(ORIGIN)
                self.add(layout)
                self.wait(0.1)
        """,
        text_line_count=1 + len(problem_lines) + len(hint_lines),
        math_expression_count=0,
        visual_description=description,
        emphasis_targets=targets,
        contains_cjk=_contains_cjk(title_text, problem_lines, hint_lines, targets),
    )


def render_equation_write(
    *,
    latex_expression: str,
    visual_description: str,
    emphasis_targets: list[str] | None = None,
) -> DeterministicTemplateRender:
    """Build a deterministic single-equation Manim scene."""
    expression = _strip_required(latex_expression, "latex_expression")
    description = _strip_required(visual_description, "visual_description")
    description_lines = _wrap_text(description, width=38, max_lines=2)
    targets = _normalize_optional_lines(emphasis_targets)
    scene_class_name = "EquationWriteScene"
    return _build_render(
        visual_type="equation_write",
        scene_class_name=scene_class_name,
        scene_source=f"""
        class {scene_class_name}(Scene):
            def construct(self):
                equation = _safe_math({expression!r}, font_size=58, color=WHITE)
                description = _text_block({description_lines!r}, font_size=24, color=GREY_B)
                layout = VGroup(equation, description)
                layout.arrange(DOWN, buff=0.5)
                _fit(layout, max_width=11.4, max_height=5.6)
                layout.move_to(ORIGIN)
                self.add(layout)
                self.wait(0.1)
        """,
        text_line_count=len(description_lines),
        math_expression_count=1,
        visual_description=description,
        emphasis_targets=targets,
        contains_cjk=_contains_cjk(expression, description_lines, targets),
    )


def render_equation_derivation(
    *,
    latex_steps: list[str],
    visual_description: str,
    emphasis_targets: list[str] | None = None,
) -> DeterministicTemplateRender:
    """Build a deterministic multi-line derivation Manim scene."""
    steps = _normalize_optional_lines(latex_steps)
    if len(steps) < 2:
        raise ValueError("latex_steps must contain at least two items")
    description = _strip_required(visual_description, "visual_description")
    description_lines = _wrap_text(description, width=42, max_lines=2)
    targets = _normalize_optional_lines(emphasis_targets)
    scene_class_name = "EquationDerivationScene"
    return _build_render(
        visual_type="equation_derivation",
        scene_class_name=scene_class_name,
        scene_source=f"""
        class {scene_class_name}(Scene):
            def construct(self):
                step_values = {steps!r}
                equations = VGroup(*[
                    _safe_math(step, font_size=42, color=WHITE)
                    for step in step_values
                ])
                equations.arrange(DOWN, aligned_edge=LEFT, buff=0.34)
                description = _text_block({description_lines!r}, font_size=23, color=GREY_B)
                description.next_to(equations, DOWN, buff=0.44)
                layout = VGroup(equations, description)
                _fit(layout, max_width=11.6, max_height=6.2)
                layout.move_to(ORIGIN)
                self.add(layout)
                self.wait(0.1)
        """,
        text_line_count=len(description_lines),
        math_expression_count=len(steps),
        visual_description=description,
        emphasis_targets=targets,
        contains_cjk=_contains_cjk(steps, description_lines, targets),
    )


def render_highlight_result(
    *,
    result_latex: str,
    visual_description: str,
    emphasis_targets: list[str] | None = None,
) -> DeterministicTemplateRender:
    """Build a deterministic final-result highlight Manim scene."""
    result = _strip_required(result_latex, "result_latex")
    description = _strip_required(visual_description, "visual_description")
    description_lines = _wrap_text(description, width=38, max_lines=2)
    targets = _normalize_optional_lines(emphasis_targets)
    scene_class_name = "HighlightResultScene"
    return _build_render(
        visual_type="highlight_result",
        scene_class_name=scene_class_name,
        scene_source=f"""
        class {scene_class_name}(Scene):
            def construct(self):
                result = _safe_math({result!r}, font_size=64, color=YELLOW)
                box = SurroundingRectangle(result, color=YELLOW, buff=0.22)
                description = _text_block({description_lines!r}, font_size=24, color=GREY_B)
                description.next_to(result, DOWN, buff=0.55)
                layout = VGroup(box, result, description)
                _fit(layout, max_width=11.4, max_height=5.8)
                layout.move_to(ORIGIN)
                self.add(layout)
                self.wait(0.1)
        """,
        text_line_count=len(description_lines),
        math_expression_count=1,
        visual_description=description,
        emphasis_targets=targets,
        contains_cjk=_contains_cjk(result, description_lines, targets),
    )


def render_outro_summary(
    *,
    summary: list[str],
    visual_description: str,
    final_answer: str | None = None,
    emphasis_targets: list[str] | None = None,
) -> DeterministicTemplateRender:
    """Build a deterministic solution-summary Manim scene."""
    summary_lines = _normalize_optional_lines(summary)[:4]
    if not summary_lines:
        raise ValueError("summary must contain at least one non-empty item")
    description = _strip_required(visual_description, "visual_description")
    answer = final_answer.strip() if final_answer is not None else None
    targets = _normalize_optional_lines(emphasis_targets)
    scene_class_name = "OutroSummaryScene"
    return _build_render(
        visual_type="outro_summary",
        scene_class_name=scene_class_name,
        scene_source=f"""
        class {scene_class_name}(Scene):
            def construct(self):
                heading = _safe_text("Summary", font_size=40, color=BLUE_E, weight="BOLD")
                summary = _text_block({summary_lines!r}, font_size=28, color=WHITE, bullet=True)
                pieces = [heading, summary]
                if {answer!r}:
                    answer = _safe_math({answer!r}, font_size=44, color=YELLOW)
                    answer.next_to(summary, DOWN, buff=0.45)
                    pieces.append(answer)
                layout = VGroup(*pieces)
                layout.arrange(DOWN, buff=0.42)
                _fit(layout, max_width=11.6, max_height=6.2)
                layout.move_to(ORIGIN)
                self.add(layout)
                self.wait(0.1)
        """,
        text_line_count=1 + len(summary_lines),
        math_expression_count=1 if answer else 0,
        visual_description=description,
        emphasis_targets=targets,
        contains_cjk=_contains_cjk(summary_lines, answer, targets),
    )
